### ISSUE TITLE
MaxActive attribute not found

### ISSUE THREAD

**Issue by viper0131** [nlighten/tomcat_exporter#10]
Hello,

Using the exporter with tomcat 8.5.33 I get the exception:

javax.management.AttributeNotFoundException: No such attribute: MaxActive

When I look at the docs of the jdbc connectionpool it looks like the MaxActive attribute should still be there.

**Comment by nlighten** [comment]
Should be fixed in version 0.0.7 which should be available in the maven repo soon.

For the impatient:
https://oss.sonatype.org/service/local/repositories/releases/content/nl/nlighten/tomcat_exporter_client/0.0.7/tomcat_exporter_client-0.0.7.jar
