### ISSUE TITLE
Tomcat 6 died when use tomcat_exporter

### ISSUE THREAD

**Issue by StartloJ** [nlighten/tomcat_exporter#14]
Hi,

I have problems on Tomcat version 6.

When I insert your suggest filter tag in [ web.xml ] on Tomcat server and restart service, my tomcat server is unavailable to access. but in newer version such as 7 , 8 it work.!!

how can I do for this case? 

thank you.

**Comment by nlighten** [comment]
I am sorry but tomcat 6 is not supported. This version also not supported by Apache anymore and does not receive security fixes anymore. My recommendation would be to upgrade to Tomcat 9.

**Comment by StartloJ** [comment]
OK.. thank you @nlighten , you can close this issue.
