### ISSUE TITLE
TomcatJdbcPoolExports initialization issue

### ISSUE THREAD

**Issue by billylamrealmatter** [nlighten/tomcat_exporter#17]
If the metrics.war deployed first the TomcatJdbcPoolExports will be disabled ?

**Comment by nlighten** [comment]
The current setup kind of assumes that the datasource is defined on server level (in server.xml and/or global context.xml). In that case the datasource should be initialized during the initilization of the metrics war. 

Are you defining the datasource in a context.xml inside your application war?

**Comment by billylamrealmatter** [comment]
Yes. My dataSource is defined inside the Application level.


Sent from my iPhone

On Feb 6, 2019, at 6:12 AM, Richard <notifications@github.com<mailto:notifications@github.com>> wrote:


The current setup kind of assumes that the datasource is defined on server level (in server.xml and/or global context.xml). In that case the datasource should be initialized during the initilization of the metrics war.

Are you defining the datasource in a context.xml inside your application war?

**Comment by nlighten** [comment]
The metrics war initialization is normally done during first scrape by prometheus. At that point the decision is made to initialize TomcatJdbcPoolExports or not (based on the existence of certain datasource mbeans). If this happens before other wars containing an context.xml with a datasource definition are started you will not see the metrics.

One solution I can think of is setting the [bindOnInit](https://tomcat.apache.org/tomcat-8.5-doc/config/http.html#Standard_Implementation) property or your connector to 'false'. Can you test this?

**Comment by billylamrealmatter** [comment]
It works with bindOnInit<https://tomcat.apache.org/tomcat-8.5-doc/config/http.html#Standard_Implementation> set to “false”.

Thanks a lot for your help.

Billy

**Comment by nlighten** [comment]
Added note to readme.
