### ISSUE TITLE
ClassNotFoundException: io.prometheus.client.exporter.MetricsServlet

### ISSUE THREAD

**Issue by AashishChughHome** [nlighten/tomcat_exporter#20]
Hi Richard,

I am getting the below error in tomcat logs while accessing metrics path.
I added all the dependencies in lib folder, still getting the error.

14-Mar-2019 05:49:55.565 SEVERE [http-nio-8080-exec-1] org.apache.catalina.core.StandardWrapperValve.invoke Allocate exception for servlet [nl.nlight en.prometheus.tomcat.TomcatMetricsServlet]                                                                                                             java.lang.ClassNotFoundException: io.prometheus.client.exporter.MetricsServlet                                                                               at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1364)                                                        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1185)                                                        at java.lang.ClassLoader.defineClass1(Native Method)                                                                                                  at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
--

**Comment by nlighten** [comment]
Can you check that you really have https://search.maven.org/search?q=a:simpleclient_servlet in the lib folder?

**Comment by AashishChughHome** [comment]
Yes i Check the file is in the same location as you described in read me file, here is the screenshot for better reach out.

![Capture](https://user-images.githubusercontent.com/29576872/54448534-00fdfd00-4772-11e9-862b-580431423ebe.PNG)

![Capture1](https://user-images.githubusercontent.com/29576872/54448548-0b1ffb80-4772-11e9-972f-fb00d1dc14b2.PNG)

**Comment by nlighten** [comment]
Please specify the versions used for the following components and I'll try to reproduce:
- tomcat
- simpleclient*.jar
- tomcat_exporter_client.jar
- tomcat_exporter_servlet.war

**Comment by rswart** [comment]
Closing due to no response.
