### ISSUE TITLE
A dashboard for this exporter?

### ISSUE THREAD

**Issue by chithanh89** [nlighten/tomcat_exporter#21]
Hi Guys,

Someone can tell me the avaiable dashboard for this exporter?
Tks so much.

**Comment by rswart** [comment]
There is no standard dashboard yet and I don't think I have time to spend on it anytime soon. Feel free to contribute one.

**Comment by vmendis** [comment]
Hi, I would like to see a Grafana based dashboard for this as well. Thank you.

**Comment by Alex1602** [comment]
I will check it out as well, a dashboard would be great

**Comment by nlighten** [comment]
The dashboard created by @albybum is now included in master branch. Note that I did not test it myself. 

I'll leave this item open for a month or so to for further comments.
