### ISSUE TITLE
Criação do contexto da aplicação no monitoramento do Pool de conexões do Datasource

### ISSUE THREAD

**Issue by rcperlin** [nlighten/tomcat_exporter#22]
Boa noite,

Realizei uma mudança no código adicionando o contexto da aplicação no monitoramento do Pool de conexões.
Caso achem interessante adicionar no aplicativo, posso enviar o código para vocês.

Só não consegui acertar os testes, não estou conseguindo simular esse comportamento sem o Tomcat.

Atenciosamente,
Rodrigo Cesar Perlin (Guina).

**Comment by rcperlin** [comment]
Esse é o fork com o código:
https://github.com/rcperlin/tomcat_exporter

**Comment by nlighten** [comment]
Afaik a datasource can be reused by multiple web applications (so multiple context roots). Wouldn't this lead to an incorrect representation of the datasource metrics?

**Comment by rcperlin** [comment]
When you create Datasource within context, a datasource is created for each context.
The Datasource control follows an example of the metrics in a Tomcat that I use:

# TYPE tomcat_jdbc_connections_max gauge
tomcat_jdbc_connections_max{pool="jdbc/JcotDS",context="/metrics",} 210.0
tomcat_jdbc_connections_max{pool="jdbc/JcotDS",context="/",} 210.0
tomcat_jdbc_connections_max{pool="jdbc/JcotDS",context="/jcotImg",} 210.0
tomcat_jdbc_connections_max{pool="jdbc/JcotDS",context="/host-manager",} 210.0
tomcat_jdbc_connections_max{pool="jdbc/JcotDS",context="/jcot-log",} 210.0
tomcat_jdbc_connections_max{pool="jdbc/JcotDS",context="/jcotapp",} 210.0
tomcat_jdbc_connections_max{pool="jdbc/JcotDS",context="/manager",} 210.0
tomcat_jdbc_connections_max{pool="jdbc/JcotDS",context="/jcotserver",} 210.0
# HELP tomcat_jdbc_connections_active_total Number of active connections allocated from this pool
# TYPE tomcat_jdbc_connections_active_total gauge
tomcat_jdbc_connections_active_total{pool="jdbc/JcotDS",context="/metrics",} 0.0
tomcat_jdbc_connections_active_total{pool="jdbc/JcotDS",context="/",} 0.0
tomcat_jdbc_connections_active_total{pool="jdbc/JcotDS",context="/jcotImg",} 0.0
tomcat_jdbc_connections_active_total{pool="jdbc/JcotDS",context="/host-manager",} 0.0
tomcat_jdbc_connections_active_total{pool="jdbc/JcotDS",context="/jcot-log",} 0.0
tomcat_jdbc_connections_active_total{pool="jdbc/JcotDS",context="/jcotapp",} 0.0
tomcat_jdbc_connections_active_total{pool="jdbc/JcotDS",context="/manager",} 0.0
tomcat_jdbc_connections_active_total{pool="jdbc/JcotDS",context="/jcotserver",} 0.0
# HELP tomcat_jdbc_connections_idle_total Number of idle connections in this pool
# TYPE tomcat_jdbc_connections_idle_total gauge
tomcat_jdbc_connections_idle_total{pool="jdbc/JcotDS",context="/metrics",} 0.0
tomcat_jdbc_connections_idle_total{pool="jdbc/JcotDS",context="/",} 0.0
tomcat_jdbc_connections_idle_total{pool="jdbc/JcotDS",context="/jcotImg",} 0.0
tomcat_jdbc_connections_idle_total{pool="jdbc/JcotDS",context="/host-manager",} 0.0
tomcat_jdbc_connections_idle_total{pool="jdbc/JcotDS",context="/jcot-log",} 0.0
tomcat_jdbc_connections_idle_total{pool="jdbc/JcotDS",context="/jcotapp",} 0.0
tomcat_jdbc_connections_idle_total{pool="jdbc/JcotDS",context="/manager",} 0.0
tomcat_jdbc_connections_idle_total{pool="jdbc/JcotDS",context="/jcotserver",} 1.0
# HELP tomcat_jdbc_connections_total Total number of connections in this pool
# TYPE tomcat_jdbc_connections_total gauge
tomcat_jdbc_connections_total{pool="jdbc/JcotDS",context="/metrics",} 0.0
tomcat_jdbc_connections_total{pool="jdbc/JcotDS",context="/",} 0.0
tomcat_jdbc_connections_total{pool="jdbc/JcotDS",context="/jcotImg",} 0.0
tomcat_jdbc_connections_total{pool="jdbc/JcotDS",context="/host-manager",} 0.0
tomcat_jdbc_connections_total{pool="jdbc/JcotDS",context="/jcot-log",} 0.0
tomcat_jdbc_connections_total{pool="jdbc/JcotDS",context="/jcotapp",} 0.0
tomcat_jdbc_connections_total{pool="jdbc/JcotDS",context="/manager",} 0.0
tomcat_jdbc_connections_total{pool="jdbc/JcotDS",context="/jcotserver",} 1.0

**Comment by rswart** [comment]
Context is added as label in the latest release (0.0.12). 

Note that if you use GlobalNamingResources to define you datasource the datasource is shared between all contexts. In this case the context label will have value 'global'.
