### ISSUE TITLE
Delayed metrics

### ISSUE THREAD

**Issue by wsams** [nlighten/tomcat_exporter#23]
I deployed the [Prometheus JMX Exporter](https://github.com/prometheus/jmx_exporter) and it has a delay option. Our applications generally spike on deployment and this option may be useful for filtering out those initial metrics. Does this tomcat exporter provide a similar option, or something that could be added? Thanks

**Comment by nlighten** [comment]
Not really. One thing you can do delay serving of metrics until all webapps have been started by setting bindOnInit option of Tomcat to false. Not sure if this is what you are looking for.

I am also not sure why you would not want to have metrics for the deployment phase. Feels like hiding the bad parts ......

**Comment by wsams** [comment]
That's a good point @nlighten . I definitely want the start up metrics, but I'm also concerned they skew the averages. I need to do some more exploration, but thought I'd at least ask. Thanks for the quick reply.

**Comment by nlighten** [comment]
Hi @wams. When using Prometheus you typically compute averages over a sliding window. E.g. last [5m]. As a result you will see a higher average during deployment for e.g. response times, but this will peak will disappear when response times have stabilized.
