### ISSUE TITLE
Syntax issue in the output

### ISSUE THREAD

**Issue by khadar-sk** [nlighten/tomcat_exporter#26]
Dear @team, 
I trying to install the tomcat exporter. I installed the tomcat exporter with the latest release.
I found that there is some syntax issue in the output.

Tomcat Exporter Output:
![tomcat-output](https://user-images.githubusercontent.com/59969428/79184821-ded22500-7e32-11ea-8816-3b184cf42f6d.JPG)

Reference:
Below 2 Exporter outputs are standard exporter supported by Prometheus
Node Exporter Output
![node-output](https://user-images.githubusercontent.com/59969428/79184853-eeea0480-7e32-11ea-8d6e-abd4eb3cc46e.JPG)

WMI Exporter Output
![wmi-output](https://user-images.githubusercontent.com/59969428/79184875-01fcd480-7e33-11ea-94a4-1d88ac538d15.JPG)

I found that there is an ',' at the labels in tomcat exporter. Due to this, I am unable to parse the syntax.

**Comment by nlighten** [comment]
The metrics are serialized using the official prometheus java client and not specific to this tomcat_exporter. It is considered valid syntax. See https://github.com/prometheus/client_java/issues/210

I have never seen prometheus having issues with parsing it. Are you parsing the output yourself?
