### ISSUE TITLE
Looking for docker platform

### ISSUE THREAD

**Issue by prasenforu** [nlighten/tomcat_exporter#3]
I want use this for container platform.

My tomcat running in docker environment.

Can you guide me how I can use this without rebuilding tomcat application  (docker)

May be I can run this as a separate container and collect metrics from  tomcat application  (docker).

**Comment by nlighten** [comment]
The exporter needs to run inside your Tomcat instance (and thus inside your container). You do not need to  modify your application war file but in the minimum scenario you need to add the jars to tomcat lib folder and the metrics war to the webapps directory.  This can be done by modifying the Dockerfile of the existing image or by creating a new image that extends you application image.
