### ISSUE TITLE
 prometheus 0.12.0 needs simpleclient_servlet_common

### ISSUE THREAD

**Issue by sstamm** [nlighten/tomcat_exporter#34]
I guess the readme needs to be adopted. 

```
<dependency>
  <groupId>io.prometheus</groupId>
  <artifactId>simpleclient_servlet_common</artifactId>
  <version>0.12.0</version>
  <type>bundle</type>
</dependency>
```

**Comment by nlighten** [comment]
I don't think this should be included in the readme as I am referring to the `pom.xml` already. 

If this was a request to update to the new Prometheus client then please close this issue as version 0.0.15 of the exporter has just been release that includes this  version.

**Comment by nlighten** [comment]
@sstamm Apologies, I initially misread your issue and thought it was about `simpleclient_servlet`. Documentation has been updated.
