### ISSUE TITLE
Add JMX Exporter features?

### ISSUE THREAD

**Issue by fdupy** [nlighten/tomcat_exporter#35]
Hello,

I would like to know if you would be open to a contribution to add features from the https://github.com/prometheus/jmx_exporter into the actual exporter ?
What I have in mind:
- I don't want to expose an additional http port so I want to avoid the java agent approach of the jmx_exporter
- in the servlet filter add an optional parameter to point to a jmx_exporter configuration file on the file system that will add a JMX Collector io.prometheus.jmx.JMXCollector

Cheers,
Fabien

**Comment by nlighten** [comment]
Hi Fabien, 

One of the original drivers to create this exporter was that that the JMX exporter was too slow. Adding it as an extra option would be conflicting with that. I would be interested to understand what type of jmx metrics you would like add through this option.  Are they Tomcat metrics or from other sources?

Please also note that I am considering ending support for this exporter by the end of 2022. Main motivation is that most deployments are now based on frameworks that already have native metric support (e.g. Spring Boot),

Rgds,

Richard

**Comment by fdupy** [comment]
Hello Richard!

Thanks a lot for the reply and clarifying the support ending date.
The JMX metric I have in mind is somehow "specific": I want to monitor the usage of a database pool (C3P0 to name it), and the datasource is created within a webapp. (I know it's counter intuitive). As you mention it, indeed my webapp will be migrated to a Spring Boot one day or later.

Rgds,
Fabien

**Comment by nlighten** [comment]
Closing as a won't do.
