### ISSUE TITLE
404 after deploying metrics.war

### ISSUE THREAD

**Issue by ttcol** [nlighten/tomcat_exporter#39]
Downloaded jar files of the latest version, moved them to my /opt/tomcat/lib/ folder. Downloaded tomcat_exporter_servlet.war, renamed it to metrics.war, added it to webapps folder that has another application of mine running. http://host:8080/metrics returns 404. Checked my logs and there is nothing significant unlike the 404. How can i resolve this?!!

**Comment by nlighten** [comment]
to be honest this does not give me a lot to go on. Could you share an `ls -la` of both the `webapps` and `lib` directories and the tomcat logs?

**Comment by ttcol** [comment]
This is the result of `ls -la` of webapps
![webapps](https://user-images.githubusercontent.com/100197540/159317770-3aba1eed-c99c-42a2-868e-88068feebfcc.png)

This is the result of `ls -la` of lib
![lib](https://user-images.githubusercontent.com/100197540/159318039-efcd4c6e-7d19-42a4-be5b-e866ab9b9ada.png)

Below is `ls -la` of my log files. You could probably specify which one I should share
![image](https://user-images.githubusercontent.com/100197540/159319809-274e1b92-362f-4235-99a6-d534ce9ce94d.png)

**Comment by nlighten** [comment]
Looks like [simpleclient_servlet_common](https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22simpleclient_servlet_common%22) is missing in the `lib` directory. Can you validate and test?

If this does not help please share the catalina.out from the time of restart.

**Comment by ttcol** [comment]
![image](https://user-images.githubusercontent.com/100197540/159422917-ed0a030d-a246-4a2c-99a2-77c17a9d3ed4.png)
Finally no 404 error. If above is the output I am supposed to receive, then thank you so much, you have saved my day. Cheers!!!!!

**Comment by nlighten** [comment]
Yes. This is the expected output.

**Comment by ttcol** [comment]
Thank you so much...!!!
