### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by devminded** [nlighten/tomcat_exporter#44]
Is this project still maintained?

I'm halfway through implementing my own and found this while looking into how to get the thread pool metrics from Tomcat.

I'm thinking of continuing with my own implementation using the Prometheus java client 1.x as well as some other features. Not really interested in the DB pools since HikariCP is superior and has it's own Prometheus exporter.

**Comment by nlighten** [comment]
Hi @devminded.

No, I have not updated this exporter for quite a long time. Nowadays we all seem to have moved to bootable app frameworks with their own build in exporters.

**Comment by devminded** [comment]
Ok. Thank you for your answer.
I'll continue building my own due to some specific use-cases in our legacy organization.
