### ISSUE TITLE
Explanation regd the Dimensions of the metrics

### ISSUE THREAD

**Issue by bytelearner007** [nlighten/tomcat_exporter#5]
Can you please add comments or explanation regd the Dimensions of the Metrics which are bit confusing to understand for people new to prometheus
 servlet_request_seconds_bucket{"/foo", "GET", "+Inf",} 1.0  <<- what does '+Inf' and especially 1.0 relates to...

**Comment by nlighten** [comment]
Thank you for your feedback. I think this is general Prometheus documentation that should not be duplicated here. For completeness sake I have added link to the Prometheus page explaining historgrams and buckets.
