### ISSUE TITLE
Oracle JDBC interceptor is not working

### ISSUE THREAD

**Issue by ricardona** [nlighten/tomcat_exporter#9]
I configured my JDBC as follows:

``` xml
<Resource name="jdbc/open_database_pooled"
          auth="Container" 
          connectionFactoryClassName="oracle.jdbc.pool.OracleDataSource"
          connectionPoolName="open_database_pooled" 
          defaultAutoCommit="false"
          factory="oracle.ucp.jdbc.PoolDataSourceImpl" 
          global="jdbc/open_database_pooled"
          inactiveConnectionTimeout="20" 
          maxPoolSize="50" 
          minPoolSize="10" 
          user="${db.user}" 
          password="secret" 
          url="${jdbc.url}" 
          type="oracle.ucp.jdbc.PoolDataSource"
          validateConnectionOnBorrow="true" 
          sqlForValidateConnection="select 1 from DUAL"
          jdbcInterceptors="nl.nlighten.prometheus.tomcat.TomcatJdbcInterceptor(logFailed=true,logSlow=true,threshold=1000,buckets=.01|.05|.1|1|10,slowQueryBuckets=1|10|30)"
          driverClassName="oracle.jdbc.driver.OracleDriver"
          defaultRowPrefetch="100000"/>
```
But as you said in the code comment, it wont work. You wrote `This interceptor will NOT work for any other connection pool (eg DBCP2).`.

Do you have some hints for creating an Oracle JDBC interceptor?

**Comment by rswart** [comment]
As indicated in the [readme ](https://github.com/nlighten/tomcat_exporter#database-response-time-metrics) the response time metrics are collected using an interceptor mechanism that is only available on the Tomcat JDBC Pool. As far as I know UCP does not support a similar mechanism so you probably need to resort to something like AOP to achieve the same thing. Another option can be to create a wrapped datasource. I'm afraid both options are not very easy to implement.

**Comment by ricardona** [comment]
Thanks for you help.
